language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - pip install coveralls pytest pytest-xdist coverage mock pylint vcrpy
install:
  - pip install .
script:
  - pylint --rcfile .pylintrc -E rtv/
  - coverage run -m py.test -v -n 4
after_success:
  - coveralls
